name: Deploy or Destroy Ephemeral Environment

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Select Action (deploy or destroy)'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy
      repo:
        description: 'GitHub Application Repository URL'
        required: true
      branch:
        description: 'Branch Name'
        required: true
      email:
        description: 'Notification Email'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run Terraform Action
        run: |
          chmod +x deploy.sh destroy.sh

          if [ "${{ github.event.inputs.action_type }}" == "deploy" ]; then
            ./deploy.sh "${{ github.event.inputs.repo }}" "${{ github.event.inputs.branch }}" "${{ github.event.inputs.email }}"
          else
            ./destroy.sh
          fi